declare class Game {
    private container;
    private elements;
    private nbCol;
    private nbLig;
    private nbCases;
    private gravity;
    private tabCases;
    private playerTurn;
    private tabPlayersContent;
    private tabPlayersName;
    private tabPlayersColor;
    private tabKeys;
    private tabKeysCol;
    private tabKeysLig;
    private chainSizeToWin;
    private tabVictories;
    private victoryCases;
    constructor(container: HTMLElement, nbCol: number, nbLig: number, chainSizeToWin: number, tabPlayersContent: any[], tabPlayersName: string[], tabPlayersColor: string[] | undefined, gravity: boolean);
    launch(): void;
    private addCases;
    private removeCases;
    private getValueOfCase;
    private getValueOfCases;
    private getCaseNumber;
    setRootVariables(): void;
    private getNumColumn;
    private getNumLine;
    private getPosition;
    private setCasesToVictory;
    private getFirstFreeCaseInColumn;
    private createEvents;
    private handleClick;
    private setPlayerTurn;
    private checkCompleted;
    private checkVictory;
    private showEnd;
    private generateVictories;
    private generateVictoriesLinesAndColumns;
    private generateVictoriesDiagonales;
}
export default Game;
