declare class Game {
    private container;
    private elements;
    private nbCol;
    private nbLig;
    private nbCases;
    private tabCases;
    private playerTurn;
    private tabPlayersContent;
    private tabKeysCol;
    private tabKeysLig;
    private chainSizeToWin;
    private tabVictories;
    constructor(container: HTMLElement, nbCol: number, nbLig: number);
    launch(): void;
    private init;
    private addCases;
    private removeCases;
    private getValueOfCase;
    private getValueOfCases;
    private getCaseNumber;
    setRootVariables(): void;
    private createEvents;
    private handleClick;
    private setPlayerTurn;
    private checkCompleted;
    private checkVictory;
    private showEnd;
    private hideEnd;
    private generateArrayVictory;
}
export default Game;
